# Generated by Django 5.0.3 on 2024-04-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_alter_quote_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='tags',
        ),
        migrations.AddField(
            model_name='tag',
            name='quotes',
            field=models.ManyToManyField(related_name='tags', to='quotes.quote'),
        ),
    ]
